### ISSUE TITLE
question

### ISSUE THREAD

**Issue by xixiaos** [OpenNLPLab/ACR_WSSS#1]
Hello author, I would like to ask if I need to create the train_mirror.sh file in your code myself, or if you have already provided it but I cannot find it in your code Thank you

**Comment by weixuansun** [comment]
it is a naming bug and I have fixed it.

**Comment by xixiaos** [comment]
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1603729128610/work/torch/lib/c10d/ProcessGroupNCCL.cpp:784, invalid usage, NCCL version 2.7.8
I want to ask why I keep reporting this error above 
Thank you

**Comment by weixuansun** [comment]
Thanks for reporting it.
The code works fine for me, could you let me know your environment including torch and cuda version.

**Comment by xixiaos** [comment]
pytorch 1.7.1 py3.6_cuda11.0.221_cudnn8.0.5_0 
CUDA Version: 11.4 
python version 3.6
torchaudio 0.7.2  py36
torchvision 0.8.2  py36_cu110 pytorch
Thank you very much

**Comment by weixuansun** [comment]
my torch version is 1.7.1, I can't reproduce this error.
I can confirm that it works fine with cuda 11.7 and cuda 10.2
